title: CartWillApps
author: Tom L Carter
email: tom@tljcarterhome.com
description: > # this means to ignore newlines until "baseurl:"
  Company of Carter & Williams.
  
# social links
twitter_username: tljcarter
github_username:  tljcarter
linkedin: tom-carter-9136422

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
