title: CartWillApps
author: Tom L Carter
email: tom@tljcarterhome.com
description: > # this means to ignore newlines until "baseurl:"
  This is a company of Carter & Williams that has been a dream for a while.
  
# social links
twitter_username: tljcarter
github_username:  tljcarter

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
